[package]
name = "g_challenges"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
comfy = "0.2.0"
sdl2 = "0.35.2"
