[package]
name = "verlet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blobs = { version = "0.2.1", features = ["tracy"] }
comfy = { version = "0.3.1", features = ["tracy"] }
